change state and change section settings gui and remote sync
OpencontentCoop/openpa pull request #9
Opened 2019-03-12 13:03 UTC by lrealdi

è possibile impostare da applicativo le configurazioni di change_state e di change_section che verranno salvate in ezsitedata 
è possibile eseguire un cambio stato su un oggetto o un cambio sezione su un nodo
le cinfigurazioni sono sincronuzzabili con istanze remote

(se necessario faccio una demo per visualizzare il funzionamento)

2019-03-13 14:00 UTC, coppo requested changes
- Inserire confirm per "reset da file di  configurazione" e "Ripristina da ultimo backup"
- Fix interfaccia editing change section
- Aggiungere confirm su elimina regola/applicazione

2019-03-13 15:15 UTC, lrealdi commented
ping @coppo

2019-03-15 17:49 UTC, lrealdi commented
ping @coppo

2019-03-15 19:19 UTC, coppo approved these changes

2019-03-15 19:20 UTC, coppo commented
Aggiungere qualche guida inline in fase di compilazione, tipo significato dei campi e sintassi.
A parte questo Squash & Lgtm

2019-03-20 14:45 UTC, merged